Globals:
    web_root: '/var/www/example.com'
    favicon: 'example.ico'
    website_title: 'amazinggamer9001.com'
    profile_image: 'test.png'
    profile_name: 'Awesome Gamer Person'
    profile_quote: "Add me on stuff!"
    profile_blurb: "A personal site for connecting with people."
    steam_URL: 'http://steamcommunity.com/id/USERID/'
    discord_username: 'coolgamer#9042'
    battlenet_tag: 'neatgamer#1010'
    twitch_channel: 'pleasewatchmeusernamename123'
    bethesda_id: 'herpderp'
   
    # setting to false will remove fork me corner banner
    fork_me: false
    # Boolean, if set to True, will generate new panel with below info
    optional_panel: False
    opt_panel_title: "OTHER THINGS"
    opt_panel_image: "IMAGE FOR THINGS"
    opt_panel_button_text: "TXT FOR THINGS"
    opt_panel_URL: "http://example.io"
